export enum ApiCodes {
  ERROR_CODE_PARAM_MISSING = 'ER0001',
  ERROR_CODE_PARAM_MISSING_MESS = 'Param is missing',
  ERROR_CODE_ERROR_SYSTEM = 'ER0002',
  ERROR_CODE_ERROR_SYSTEM_MESS = 'System is error',
  ERROR_CODE_USER_LOGIN_WAS_EXISTING = 'MSG0044',
  ERROR_CODE_USER_LOGIN_WAS_EXISTING_MESS = 'UserLogin was existing',
  ERROR_CODE_USER_IS_NOT_EXISTING = 'MSG0020',
  ERROR_CODE_USER_IS_NOT_EXISTING_MESS = 'User is not existing',
  ERROR_CODE_USER_OR_PASSWORD_IS_NOT_CORRECT = 'MSG0021',
  ERROR_CODE_USER_OR_PASSWORD_IS_NOT_CORRECT_MESS = 'User or Password is not correct',
  ERROR_CODE_OTP_EXPIRED = 'MSG0043',
  ERROR_CODE_OTP_EXPIRED_MESS = 'OTP was expired',
  ERROR_CODE_OTP_IS_NOT_CORRECT = 'MSG0008',
  ERROR_CODE_OTP_IS_NOT_CORRECT_MESS = 'OTP is not correct',
  ERROR_CODE_USER_IS_DISABLE = 'MSG0045',
  ERROR_CODE_USER_IS_DISABLE_MESS = 'User is disable',
  ERROR_CODE_USER_IS_INACTIVE = 'MSG0046',
  ERROR_CODE_USER_IS_INACTIVE_MESS = 'User is inactived',

  ERROR_CODE_OTP_WAS_BLOCKED = 'MSG0047',
  ERROR_CODE_OTP_WAS_BLOCKED_MESS = 'OTP was blocked',
  ERROR_CODE_UUID_IS_NOT_CORRECT = 'MSG0049',
  ERROR_CODE_UUID_IS_NOT_CORRECT_MESS = 'UUID is not correct',
  ERROR_CODE_USER_HAVE_BLOCKED_OTP = 'MSG0050',
  ERROR_CODE_USER_HAVE_BLOCKED_OTP_MESS = 'User have blocked OTP',
  ERROR_CODE_CATEGORY_IS_NOT_EXISTING = 'MSG0051',
  ERROR_CODE_CATEGORY_IS_NOT_EXISTING_MESS = 'Category is not existing',
  ERROR_CODE_PRODUCT_IS_NOT_EXISTING = 'MSG0052',
  ERROR_CODE_PRODUCT_IS_NOT_EXISTING_MESS = 'Product is not existing',
  ERROR_CODE_SELLER_IS_NOT_EXISTING = 'MSG0053',
  ERROR_CODE_SELLER_IS_NOT_EXISTING_MESS = 'Seller is not existing',
  ERROR_CODE_SELLER_INFO_IS_NOT_UPDATED = 'MSG0054',
  ERROR_CODE_SELLER_INFO_IS_NOT_UPDATED_MESS = 'Seller Info is not updated',
  ERROR_CODE_SELLER_DOCUMENT_IS_NOT_UPDATED = 'MSG0055',
  ERROR_CODE_SELLER_DOCUMENT_IS_NOT_UPDATED_MESS = 'Seller Document is not updated',
  ERROR_CODE_SELLER_AGREEMENT_IS_NOT_UPDATED = 'MSG0056',
  ERROR_CODE_SELLER_AGREEMENT_IS_NOT_UPDATED_MESS = 'Seller Agreement is not updated',
  ERROR_CODE_AGREEMENT_IS_NOT_EXISTING = 'MSG0057',
  ERROR_CODE_AGREEMENT_IS_NOT_EXISTING_MESS = 'Agreement is not existing',
  ERROR_CODE_SELLER_LOGIN_WAS_EXISTING = 'MSG0058',
  ERROR_CODE_SELLER_LOGIN_WAS_EXISTING_MESS = 'Seller Login was existing',
  ERROR_CODE_SELLER_OR_PASSWORD_IS_NOT_CORRECT = 'MSG0059',
  ERROR_CODE_SELLER_OR_PASSWORD_IS_NOT_CORRECT_MESS = 'Seller or Password is not correct',
  ERROR_CODE_SELLER_IS_DISABLE = 'MSG0060',
  ERROR_CODE_SELLER_IS_DISABLE_MESS = 'Seller is disable',
  ERROR_CODE_SELLER_IS_INACTIVE = 'MSG0061',
  ERROR_CODE_SELLER_IS_INACTIVE_MESS = 'Seller is inactived',
  ERROR_CODE_SELLER_HAVE_BLOCKED_OTP = 'MSG0062',
  ERROR_CODE_SELLER_HAVE_BLOCKED_OTP_MESS = 'Seller have blocked OTP',
  ERROR_CODE_SELLER_UPDATED_INFO = 'MSG0063',
  ERROR_CODE_SELLER_UPDATED_INFO_MESS = 'Seller updated Info',

  ERROR_CODE_SELLER_IS_NOT_INDIVIDUAL = 'MSG0064',
  ERROR_CODE_SELLER_IS_NOT_INDIVIDUAL_MESS = 'Seller is not Individual',

  //file
  ERROR_CODE_FILE_UPLOAD_IS_NOT_EXISTING = 'MSG0065',
  ERROR_CODE_FILE_UPLOAD_IS_NOT_EXISTING_MESS = 'File upload is not existing.',

  ERROR_CODE_PRODUCT_SKU_IS_NOT_EXISTING = 'MSG0066',
  ERROR_CODE_PRODUCT_SKU_IS_NOT_EXISTING_MESS = 'Product SKU is not existing',

  ERROR_CODE_USER_TYPE_IS_NOT_CORRECT = 'MSG0067',
  ERROR_CODE_USER_TYPE_IS_NOT_CORRECT_MESS = 'User Type is not correct',

  ERROR_CODE_CART_IS_EMPTY = 'MSG0068',
  ERROR_CODE_CART_IS_EMPTY_MESS = 'Cart is empty',

  ERROR_CODE_PHONE_OF_SELLER_IS_NOT_EXISTING = 'MSG0069',
  ERROR_CODE_PHONE_OF_SELLER_IS_NOT_EXISTING_MESS = 'Phone of Seller is not existing',

  ERROR_CODE_CITY_IS_NOT_EXISTING = 'MSG0070',
  ERROR_CODE_CITY_IS_NOT_EXISTING_MESS = 'City is not existing',

  ERROR_CODE_RECEIVER_ADDRESS_IS_NOT_EXISTING = 'MSG0071',
  ERROR_CODE_RECEIVER_ADDRESS_IS_NOT_EXISTING_MESS = 'Receiver Address is not existing',

  ERROR_CODE_CART_IS_NOT_EXISTING = 'MSG0072',
  ERROR_CODE_CART_IS_NOT_EXISTING_MESS = 'Cart is not existing',

  ERROR_CODE_PERSON_FILE_CITIZEN_BEFORE_EMPTY = 'MSG0073',
  ERROR_CODE_PERSON_FILE_CITIZEN_BEFORE_EMPTY_MESS = 'File Citizen Before is empty',

  ERROR_CODE_PERSON_FILE_CITIZEN_AFTER_EMPTY = 'MSG0074',
  ERROR_CODE_PERSON_FILE_CITIZEN_AFTER_EMPTY_MESS = 'File Citizen After is empty',

  ERROR_CODE_SELLER_INFO_IS_EMPTY = 'MSG0075',
  ERROR_CODE_SELLER_INFO_IS_EMPTY_MESS = 'Seller Info is empty',

  ERROR_CODE_BUSINESS_FILE_LICENSE_EMPTY = 'MSG0076',
  ERROR_CODE_BUSINESS_FILE_LICENSE_EMPTY_MESS = 'Business File License is empty',

  ERROR_CODE_SELLER_IS_NOT_BUSINESS = 'MSG0077',
  ERROR_CODE_SELLER_IS_NOT_BUSINESSL_MESS = 'Seller is not Business',

  ERROR_CODE_BUSINESS_TYPE_IS_NOT_CORRECT = 'MSG0078',
  ERROR_CODE_BUSINESS_TYPE_IS_NOT_CORRECT_MESS = 'Business Type is not correct',

  ERROR_CODE_PERSON_DOCUMENT_HAS_NOT_BEEN_UPDATED = 'MSG0079',
  ERROR_CODE_PERSON_DOCUMENT_HAS_NOT_BEEN_UPDATED_MESS = 'Person document has not been updated',

  ERROR_CODE_BUSINESS_DOCUMENT_HAS_NOT_BEEN_UPDATED = 'MSG0080',
  ERROR_CODE_BUSINESS_DOCUMENT_HAS_NOT_BEEN_UPDATED_MESS = 'Business document has not been updated',

  ERROR_CODE_AGREEMENT_WAS_ADDED = 'MSG0081',
  ERROR_CODE_AGREEMENT_WAS_ADDED_MESS = 'Agreement was added',

  ERROR_CODE_ORDER_IS_EMPTY = 'MSG0082',
  ERROR_CODE_ORDER_IS_EMPTY_MESS = 'Order is empty',

  ERROR_CODE_ORDER_IS_NOT_EXISTING = 'MSG0083',
  ERROR_CODE_ORDER_IS_NOT_EXISTING_MESS = 'Order is not existing',
}
