import { IMcMenuItem } from '@shared/models';
import { RouteUtils } from '@shared/utils';
import { eRoles } from '@shared/enums';

export type HomeMenuItem = IMcMenuItem & {
  infoItems?: { title: string; count: number; type?: 'green' | 'default' }[];
  roles?: eRoles[];
  permissions?: string[];
};

export const HOME_MENU: HomeMenuItem[] = [
  {
    id: 'categories',
    title: 'menu.categories.card',
    icon: 'square-four',
    link: ['/', RouteUtils.CategoriesPage.Base],
    type: 'collapse',
    level: 1,
    infoItems: [
      { title: 'Chờ duyệt', count: 0 },
      { title: 'Đã duyệt', count: 0, type: 'green' },
    ],
    children: [],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.DataAdmin],
    permissions: [],
  },
  {
    id: 'policies',
    title: 'menu.policies.card',
    icon: 'certificate',
    link: ['/', RouteUtils.ProgramPoliciesPage.Base],
    type: 'collapse',
    level: 1,
    children: [],
    infoItems: [
      { title: 'Chờ duyệt', count: 0 },
      { title: 'Đã duyệt', count: 0, type: 'green' },
    ],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.DataAdmin],
    permissions: [],
  },
  {
    id: 'location',
    title: 'menu.location',
    icon: 'map-pin-line',
    link: ['/', RouteUtils.AreaTreePage.Base],
    type: 'collapse',
    level: 1,
    infoItems: [
      { title: 'Chờ duyệt', count: 0 },
      { title: 'Đã duyệt', count: 0, type: 'green' },
    ],
    children: [],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.DataAdmin],
    permissions: [],
  },
  {
    id: 'notifications',
    title: 'menu.notifications',
    icon: 'bell-ringing',
    link: RouteUtils.NotificationManagement.Base,
    type: 'collapse',
    level: 1,
    children: [],
    infoItems: [
      { title: 'Chờ duyệt', count: 0 },
      { title: 'Đã duyệt', count: 0, type: 'green' },
    ],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.DataAdmin],
    permissions: [],
    disabled: false,
  },
  {
    id: 'agreements',
    title: 'menu.agreements',
    icon: 'scroll',
    link: [RouteUtils.AgreementPage.Base],
    type: 'collapse',
    level: 1,
    children: [],
    infoItems: [
      { title: 'Chờ duyệt', count: 0 },
      { title: 'Đã duyệt', count: 0, type: 'green' },
    ],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.DataAdmin],
    permissions: [],
  },
  {
    id: 'control',
    title: 'menu.control',
    icon: 'reconciliation-outlined',
    link: ['#'],
    type: 'collapse',
    level: 1,
    infoItems: [
      { title: 'Chờ đối soát', count: 0 },
      { title: 'Đang đối soát', count: 0, type: 'green' },
    ],
    children: [],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.AccountantAdmin],
    permissions: [],
  },
  {
    id: 'payment',
    title: 'menu.payment',
    icon: 'currency-circle-dollar',
    link: ['#'],
    type: 'collapse',
    level: 1,
    infoItems: [
      { title: 'Chờ thanh toán', count: 0 },
      { title: 'Đã thanh toán', count: 0, type: 'green' },
    ],
    children: [],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.AccountantAdmin],
    permissions: [],
  },
  {
    id: 'refund',
    title: 'menu.refund',
    icon: 'refund-2-line',
    link: ['#'],
    type: 'collapse',
    level: 1,
    infoItems: [
      { title: 'Chờ hoàn tiền', count: 0 },
      { title: 'Đã hoàn tiền', count: 0, type: 'green' },
    ],
    children: [],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.AccountantAdmin],
    permissions: [],
  },
  {
    id: 'report',
    title: 'menu.report',
    icon: 'report',
    link: ['#'],
    type: 'collapse',
    level: 1,
    infoItems: [
      { title: 'Tổng thu', count: 0 },
      { title: 'Tổng chi', count: 0, type: 'green' },
    ],
    children: [],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.AccountantAdmin],
    permissions: [],
  },
  {
    id: 'general_setting',
    title: 'menu.general_setting',
    icon: 'gear',
    link: [RouteUtils.GeneralSettingPage.Base],
    type: 'collapse',
    level: 1,
    children: [],
    infoItems: [
      { title: 'Chờ duyệt', count: 0 },
      { title: 'Đã duyệt', count: 0, type: 'green' },
    ],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.DataAdmin],
    permissions: [],
  },
  {
    id: 'permissions',
    title: 'menu.permissions',
    icon: 'permission',
    link: ['#'],
    type: 'collapse',
    level: 1,
    children: [],
    infoItems: [
      { title: 'Roles', count: 0 },
      { title: 'Users', count: 0, type: 'green' },
    ],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.DataAdmin],
    permissions: [],
    disabled: true,
  },
  {
    id: 'contact',
    title: 'menu.contact-and-support',
    icon: 'personal-support',
    link: [RouteUtils.ContactAndSupport.Contact],
    type: 'item',
    level: 1,
    children: [],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.DataAdmin],
    permissions: [],
    disabled: false,
  },
  {
    id: 'data-qa',
    title: 'menu.qa',
    icon: 'qa-chat-box',
    link: [RouteUtils.QuestionAndAnswer.Base],
    type: 'collapse',
    level: 1,
    infoItems: [
      { title: 'Chờ duyệt', count: 0 },
      { title: 'Đã duyệt', count: 0, type: 'green' },
    ],
    children: [],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.DataAdmin],
    permissions: [],
  },
  {
    id: 'banks',
    title: 'menu.banks.card',
    icon: 'bank',
    link: ['/', RouteUtils.BanksPage.Base],
    type: 'collapse',
    level: 1,
    children: [],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.DataAdmin],
    permissions: [],
    infoItems: [{ title: 'Danh sách', count: 0, type: 'green' }],
  },
  {
    id: 'users',
    title: 'menu.users',
    icon: 'user',
    link: ['/', RouteUtils.UsersPage.Base],
    type: 'collapse',
    level: 1,
    children: [],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.DataAdmin],
    permissions: [],
    infoItems: [
      { title: 'Bị khoá', count: 0 },
      { title: 'Đang sử dụng', count: 0, type: 'green' },
    ],
  },
  {
    id: 'community-standards',
    title: 'menu.community_standards.base',
    icon: 'users-three',
    link: ['/', RouteUtils.CommunityStandards.Base],
    type: 'collapse',
    level: 1,
    children: [],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.DataAdmin],
    permissions: [],
  },
  {
    id: 'community-standards-approval',
    title: 'menu.community_standards.approval',
    icon: 'users-three',
    link: ['/', RouteUtils.CommunityStandards.Approval, RouteUtils.CommunityStandards.Base],
    type: 'collapse',
    level: 1,
    children: [],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.OperationAdmin],
    permissions: [],
  },
  {
    id: 'products',
    title: 'menu.products',
    icon: 'package',
    link: ['products'],
    type: 'collapse',
    level: 1,
    infoItems: [
      { title: 'Chờ duyệt', count: 0 },
      { title: 'Đã duyệt', count: 0, type: 'green' },
    ],
    children: [],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.OperationAdmin],
    permissions: [],
  },
  {
    id: 'programs',
    title: 'menu.programs',
    icon: 'gift',
    link: ['/', RouteUtils.ProgramsPage.Base],
    // link: ['#'],
    type: 'collapse',
    level: 1,
    children: [],
    infoItems: [
      { title: 'Chờ duyệt', count: 0 },
      { title: 'Đã duyệt', count: 0, type: 'green' },
    ],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.OperationAdmin],
    permissions: [],
  },
  {
    id: 'registering_profiles',
    title: 'menu.registering_profiles.card',
    icon: 'clipboard',
    link: ['/', RouteUtils.ProfilesPage.Base],
    type: 'collapse',
    level: 1,
    infoItems: [
      { title: 'Chờ duyệt', count: 0 },
      { title: 'Đã duyệt', count: 0, type: 'green' },
    ],
    children: [],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.OperationAdmin],
    permissions: [],
  },
  {
    id: 'categories',
    title: 'menu.categories.card-approval',
    icon: 'square-four',
    link: ['/', RouteUtils.CategoriesPage.Base],
    type: 'collapse',
    level: 1,
    infoItems: [
      { title: 'Chờ duyệt', count: 0 },
      { title: 'Đã duyệt', count: 0, type: 'green' },
    ],
    children: [],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.OperationAdmin],
    permissions: [],
    disabled: true,
  },
  {
    id: 'groups',
    title: 'menu.groups_approval',
    icon: 'circles',
    // link: ['/', RouteUtils.CategoriesPage.Groups],
    link: ['#'],
    type: 'collapse',
    level: 1,
    infoItems: [
      { title: 'Chờ duyệt', count: 0 },
      { title: 'Đã duyệt', count: 0, type: 'green' },
    ],
    children: [],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.OperationAdmin],
    permissions: [],
    disabled: true,
  },
  {
    id: 'notifications-approval',
    title: 'menu.notification_approval',
    icon: 'bell-ringing',
    link: ['#'],
    type: 'collapse',
    level: 1,
    children: [],
    infoItems: [
      { title: 'Chờ duyệt', count: 0 },
      { title: 'Đã duyệt', count: 0, type: 'green' },
    ],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.OperationAdmin],
    permissions: [],
    disabled: true,
  },
  {
    id: 'agreements',
    title: 'menu.agreements_approval',
    icon: 'scroll',
    link: ['#'],
    type: 'collapse',
    level: 1,
    children: [],
    infoItems: [
      { title: 'Chờ duyệt', count: 0 },
      { title: 'Đã duyệt', count: 0, type: 'green' },
    ],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.OperationAdmin],
    permissions: [],
    disabled: true,
  },
  {
    id: 'op-qa',
    title: 'menu.qa-approval',
    icon: 'qa-chat-box',
    link: ['#'],
    type: 'collapse',
    level: 1,
    infoItems: [
      { title: 'Chờ duyệt', count: 0 },
      { title: 'Đã duyệt', count: 0, type: 'green' },
    ],
    children: [],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.OperationAdmin],
    permissions: [],
    disabled: true,
  },
  {
    id: 'sellers',
    title: 'menu.sellers',
    icon: 'sales-ops',
    link: ['#'],
    type: 'collapse',
    level: 1,
    infoItems: [
      { title: 'Mới', count: 0 },
      { title: 'Tổng', count: 0, type: 'green' },
    ],
    children: [],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.CustomerServiceAdmin],
    permissions: [],
  },
  {
    id: 'customer',
    title: 'menu.customer',
    icon: 'customer',
    link: ['#'],
    type: 'collapse',
    level: 1,
    infoItems: [
      { title: 'Mới', count: 0 },
      { title: 'Tổng', count: 0, type: 'green' },
    ],
    children: [],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.CustomerServiceAdmin],
    permissions: [],
  },
  {
    id: 'customer-report',
    title: 'report_page.title',
    icon: 'flag',
    link: ['/', RouteUtils.ReportsPage.Base],
    type: 'collapse',
    level: 1,
    infoItems: [
      { title: 'Mới', count: 0 },
      { title: 'Đã xử lý', count: 0, type: 'green' },
    ],
    children: [],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.CustomerServiceAdmin],
    permissions: [],
  },
  {
    id: 'customer-feedback',
    title: 'feedback_page.title',
    icon: 'outline-info',
    link: ['/', RouteUtils.FeedbacksPage.Base],
    type: 'collapse',
    level: 1,
    infoItems: [
      { title: 'Mới', count: 0 },
      { title: 'Đã xử lý', count: 0, type: 'green' },
    ],
    children: [],
    hasWarning: false,
    roles: [eRoles.SuperAdmin, eRoles.CustomerServiceAdmin],
    permissions: [],
  },
];
