import { IMcMenuItem } from '@shared/models';
import { RouteUtils } from '@shared/utils';
import {
  eAccountStatus,
  eContentStatuses,
  eFeedbackFilterType,
  eMenuClickEvents,
  ePackedUnitType,
  eReportContentStatus,
  eReportType,
} from '@shared/enums';

export type MenuItemWithCounter = Omit<IMcMenuItem, 'type'> & {
  collapsed?: boolean;
  count?: number;
  type: IMcMenuItem['type'] | 'divider';
  children?: Array<IMcMenuItem & { count?: number; onClick?: () => void }>;
  onClick?: () => void;
  emitEvent?: eMenuClickEvents;
};

export const PACKED_UNIT_MENU_ITEMS: MenuItemWithCounter[] = [
  {
    id: 'packing',
    title: 'Đóng gói',
    link: ['.'],
    type: 'item',
    level: 2,
    queryParams: { type: ePackedUnitType.Packing },
  },
  {
    id: 'selling',
    title: 'Đơn vị bán',
    link: ['.'],
    type: 'item',
    queryParams: { type: ePackedUnitType.Selling },
    level: 2,
  },
];

export const FEEDBACK_MENU_ITEMS: MenuItemWithCounter[] = [
  {
    id: 'feedback',
    title: 'Góp ý',
    icon: 'outline-info',
    link: ['/', RouteUtils.FeedbacksPage.Base],
    type: 'item',
    level: 1,
    children: [
      {
        id: eFeedbackFilterType.New.toString(),
        title: 'enums.content_statuses.new',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eFeedbackFilterType.New },
      },
      {
        id: eFeedbackFilterType.Reviewing.toString(),
        title: 'enums.content_statuses.admin_processing',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eFeedbackFilterType.Reviewing },
      },
      {
        id: eFeedbackFilterType.Handled.toString(),
        title: 'enums.content_statuses.admin_processed',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eFeedbackFilterType.Handled },
      },
      {
        id: eFeedbackFilterType.Useful.toString(),
        title: 'enums.content_statuses.useful',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eFeedbackFilterType.Useful },
      },
    ],
  },
];

export const REPORT_MENU_ITEMS: MenuItemWithCounter[] = [
  {
    id: eReportType.Rating,
    title: 'Đánh giá',
    icon: 'outline-star',
    link: ['/', RouteUtils.ReportsPage.Base, RouteUtils.ReportsPage.RatingReport],
    type: 'item',
    level: 1,
    hasWarning: false,
    children: [
      {
        id: eReportContentStatus.New.toString(),
        title: 'enums.content_statuses.new',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eReportContentStatus.New },
      },
      {
        id: eReportContentStatus.Reviewing.toString(),
        title: 'enums.content_statuses.admin_processing',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eReportContentStatus.Reviewing },
      },
      {
        id: eReportContentStatus.Handled.toString(),
        title: 'enums.content_statuses.admin_processed',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eReportContentStatus.Handled },
      },
    ],
  },
  {
    id: eReportType.Message,
    title: 'Tin nhắn',
    icon: 'outline-chat-circle-text',
    link: ['/', RouteUtils.ReportsPage.Base, RouteUtils.ReportsPage.MessageReport],
    type: 'item',
    level: 1,
    children: [
      {
        id: eReportContentStatus.New.toString(),
        title: 'enums.content_statuses.new',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eReportContentStatus.New },
      },
      {
        id: eReportContentStatus.Reviewing.toString(),
        title: 'enums.content_statuses.admin_processing',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eReportContentStatus.Reviewing },
      },
      {
        id: eReportContentStatus.Handled.toString(),
        title: 'enums.content_statuses.admin_processed',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eReportContentStatus.Handled },
      },
    ],
  },
  {
    id: eReportType.Shop,
    title: 'Shop',
    icon: 'outline-store-front',
    link: ['/', RouteUtils.ReportsPage.Base, RouteUtils.ReportsPage.SellerReport],
    type: 'item',
    hasWarning: false,
    level: 1,
    children: [
      {
        id: eReportContentStatus.New.toString(),
        title: 'enums.content_statuses.new',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eReportContentStatus.New },
      },
      {
        id: eReportContentStatus.Reviewing.toString(),
        title: 'enums.content_statuses.admin_processing',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eReportContentStatus.Reviewing },
      },
      {
        id: eReportContentStatus.Handled.toString(),
        title: 'enums.content_statuses.admin_processed',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eReportContentStatus.Handled },
      },
    ],
  },
];

export const ACCOUNT_MENU_ITEMS: MenuItemWithCounter[] = [
  {
    id: 'info',
    title: 'Thông tin chung',
    link: ['/', RouteUtils.ProfilePage.Base, RouteUtils.AccountPage.DetailInfo],
    type: 'item',
    icon: 'user',
    level: 1,
  },
  {
    id: 'messages',
    title: 'Tin nhắn',
    link: ['#'],
    type: 'item',
    icon: 'bubble-chat',
    level: 1,
  },
  {
    id: 'account',
    title: 'Tài khoản, mật khẩu',
    icon: 'package',
    link: ['/', RouteUtils.ProfilePage.Base, RouteUtils.UsersPage.DetailControlPanel],
    type: 'item',
    level: 1,
  },
  {
    id: 'notifications',
    title: 'Thông báo',
    icon: 'bell',
    link: ['#'],
    type: 'item',
    level: 1,
  },
  {
    id: 'divider1',
    type: 'divider' as any,
  },
  {
    id: 'sign-out',
    type: 'item',
    level: 1,
    icon: 'sign-out',
    link: ['#'],
    title: 'Đăng xuất',
    emitEvent: eMenuClickEvents.SignOut,
  },
];

export const USER_MENU_ITEMS: MenuItemWithCounter[] = [
  {
    id: 'info',
    title: 'Thông tin chung',
    link: ['.', RouteUtils.UsersPage.DetailInfo],
    type: 'item',
    icon: 'package',
    level: 1,
  },
  {
    id: 'account',
    title: 'Tài khoản, mật khẩu',
    icon: 'package',
    link: ['.', RouteUtils.UsersPage.DetailControlPanel],
    type: 'item',
    level: 1,
  },
];

export const PROGRAM_MENU_ITEMS: MenuItemWithCounter[] = [
  {
    id: eContentStatuses.AdminPending.toString(),
    title: 'enums.content_statuses.admin_pending',
    link: ['.'],
    type: 'item',
    level: 2,
    queryParams: { status: eContentStatuses.AdminPending },
  },
  {
    id: eContentStatuses.AdminReviewing.toString(),
    title: 'enums.content_statuses.admin_reviewing',
    link: ['.'],
    type: 'item',
    level: 2,
    queryParams: { status: eContentStatuses.AdminReviewing },
  },
  {
    id: eContentStatuses.AdminRejected.toString(),
    title: 'enums.content_statuses.admin_rejected',
    link: ['.'],
    type: 'item',
    level: 2,
    queryParams: { status: eContentStatuses.AdminRejected },
  },
  {
    id: eContentStatuses.AdminApproved.toString(),
    title: 'enums.content_statuses.admin_approved',
    link: ['.'],
    type: 'item',
    level: 2,
    queryParams: { status: eContentStatuses.AdminApproved },
  },
];
export const PROFILE_MENU_ITEMS: MenuItemWithCounter[] = [
  // {
  //   id: eContentStatuses.All.toString(),
  //   title: 'enums.content_statuses.all',
  //   link: ['.'],
  //   type: 'item',
  //   level: 2,
  //   queryParams: { status: eContentStatuses.All },
  // },
  {
    id: eContentStatuses.AdminPending.toString(),
    title: 'enums.content_statuses.admin_pending',
    link: ['.'],
    type: 'item',
    level: 2,
    queryParams: { status: eContentStatuses.AdminPending },
  },
  {
    id: eContentStatuses.AdminReviewing.toString(),
    title: 'enums.content_statuses.admin_reviewing',
    link: ['.'],
    type: 'item',
    level: 2,
    queryParams: { status: eContentStatuses.AdminReviewing },
  },
  {
    id: eContentStatuses.AdminApproved.toString(),
    title: 'enums.content_statuses.admin_approved',
    link: ['.'],
    type: 'item',
    level: 2,
    queryParams: { status: eContentStatuses.AdminApproved },
  },
  {
    id: eContentStatuses.AdminRejected.toString(),
    title: 'enums.content_statuses.admin_rejected',
    link: ['.'],
    type: 'item',
    level: 2,
    queryParams: { status: eContentStatuses.AdminRejected },
  },
  // {
  //   id: eContentStatuses.AdminHidden.toString(),
  //   title: 'enums.content_statuses.hidden',
  //   link: ['.'],
  //   type: 'item',
  //   level: 2,
  //   queryParams: { status: eContentStatuses.AdminHidden },
  // },
  // {
  //   id: eContentStatuses.AdminArchived.toString(),
  //   title: 'enums.content_statuses.archived',
  //   link: ['.'],
  //   type: 'item',
  //   level: 2,
  //   queryParams: { status: eContentStatuses.AdminArchived },
  // },
];

export const BANK_MENU_ITEMS: MenuItemWithCounter[] = [
  {
    id: 'banks',
    title: 'menu.banks.base',
    icon: 'bank',
    link: ['/', RouteUtils.BanksPage.Base],
    type: 'collapse',
    level: 1,
    children: [
      {
        id: eContentStatuses.All,
        title: 'enums.content_statuses.all',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      {
        id: eContentStatuses.Draft,
        title: 'enums.content_statuses.draft',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.Draft },
      },
      {
        id: eContentStatuses.AdminPending,
        title: 'enums.content_statuses.admin_pending',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminPending },
      },
      {
        id: eContentStatuses.AdminReviewing,
        title: 'enums.content_statuses.admin_reviewing',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminReviewing },
      },
      {
        id: eContentStatuses.AdminRejected,
        title: 'enums.content_statuses.admin_rejected',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminRejected },
      },
      {
        id: eContentStatuses.AdminApproved,
        title: 'enums.content_statuses.admin_approved',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminApproved },
      },
      // {
      //   id: 'admin_archived',
      //   title: 'enums.content_statuses.admin_archived',
      //   icon: 'plus',
      //   link: ['.'],
      //   type: 'item',
      //   level: 2,
      //   queryParams: { status: eContentStatuses.AdminArchived },
      // },
    ],
    hasWarning: false,
  },
];

export const CATEGORY_MENU_ITEMS: MenuItemWithCounter[] = [
  {
    id: 'categories',
    title: 'menu.categories.base',
    icon: 'product-list',
    link: ['/', RouteUtils.CategoriesPage.Base],
    type: 'collapse',
    level: 1,
    children: [
      {
        id: eContentStatuses.All,
        title: 'enums.content_statuses.all',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      {
        id: eContentStatuses.Draft,
        title: 'enums.content_statuses.draft',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.Draft },
      },
      {
        id: eContentStatuses.AdminPending,
        title: 'enums.content_statuses.admin_pending',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminPending },
      },
      {
        id: eContentStatuses.AdminReviewing,
        title: 'enums.content_statuses.admin_reviewing',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminReviewing },
      },
      {
        id: eContentStatuses.AdminRejected,
        title: 'enums.content_statuses.admin_rejected',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminRejected },
      },
      {
        id: eContentStatuses.AdminApproved,
        title: 'enums.content_statuses.admin_approved',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminApproved },
      },
      {
        id: eContentStatuses.AdminArchived,
        title: 'enums.content_statuses.admin_archived',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminArchived },
      },
    ],
    hasWarning: false,
  },
  {
    id: 'groups',
    title: 'menu.groups',
    icon: 'group',
    link: ['/', 'groups'],
    type: 'item',
    level: 1,
    hasWarning: false,
  },
  {
    id: 'product_units',
    title: 'menu.categories.product_units',
    icon: 'packages',
    link: ['/', RouteUtils.PackedUnitsPage.Base],
    type: 'item',
    level: 1,
    children: [],
    hasWarning: false,
  },
  // {
  //   id: 'sizing_units',
  //   title: 'menu.categories.siz  ing_units',
  //   icon: 'codepen',
  //   link: ['#'],
  //   type: 'item',
  //   level: 1,
  //   children: [],
  //   hasWarning: false,
  // },
  // {
  //   id: 'volume_units',
  //   title: 'menu.categories.volume_units',
  //   icon: 'drop-half',
  //   link: ['#'],
  //   type: 'item',
  //   level: 1,
  //   children: [],
  //   hasWarning: false,
  // },
  // {
  //   id: 'weight_units',
  //   title: 'menu.categories.weight_units',
  //   icon: 'test-tube',
  //   link: ['#'],
  //   type: 'item',
  //   level: 1,
  //   children: [],
  //   hasWarning: false,
  // },
];

export const PRIVACY_POLICIES_MENU_ITEMS: MenuItemWithCounter[] = [
  {
    id: 'sale-fee-policies',
    title: 'menu.policies.sale_fee',
    icon: 'money',
    link: ['/'],
    type: 'item',
    level: 1,
    hasWarning: false,
  },
  {
    id: 'transport-fee-policies',
    title: 'menu.policies.transport_fee',
    icon: 'hand-coins',
    link: ['/'],
    type: 'item',
    level: 1,
    hasWarning: false,
  },
  {
    id: 'debt-policies',
    title: 'menu.policies.debt',
    icon: 'calculator',
    link: ['/'],
    type: 'item',
    level: 1,
    hasWarning: false,
  },
  {
    id: 'organization_registration-policies',
    title: 'menu.policies.organization_registration',
    icon: 'buildings',
    link: ['/'],
    type: 'item',
    level: 1,
    hasWarning: false,
  },
  {
    id: 'program-policies',
    title: 'menu.policies.program',
    icon: 'gift',
    link: ['/', RouteUtils.ProgramPoliciesPage.Base],
    type: 'item',
    level: 1,
    hasWarning: false,
  },
  {
    id: 'privacy-policies',
    title: 'menu.policies.privacy',
    icon: 'gift',
    link: ['/', RouteUtils.PrivacyPoliciesPage.Base],
    type: 'collapse',
    level: 1,
    hasWarning: false,
    children: [
      {
        id: eContentStatuses.All,
        title: 'enums.content_statuses.all',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      {
        id: eContentStatuses.Draft,
        title: 'enums.content_statuses.draft',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.Draft },
      },
      {
        id: eContentStatuses.AdminPending,
        title: 'enums.content_statuses.admin_pending',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminPending },
      },
      {
        id: eContentStatuses.AdminReviewing,
        title: 'enums.content_statuses.admin_reviewing',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminReviewing },
      },
      {
        id: eContentStatuses.AdminRejected,
        title: 'enums.content_statuses.admin_rejected',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminRejected },
      },
      {
        id: eContentStatuses.AdminApproved,
        title: 'enums.content_statuses.admin_approved',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminApproved },
      },
      {
        id: eContentStatuses.AdminArchived,
        title: 'enums.content_statuses.admin_archived',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminArchived },
      },
    ],
  },
  {
    id: 'transport-policies',
    title: 'menu.policies.transport',
    icon: 'truck',
    link: ['/'],
    type: 'item',
    level: 1,
    hasWarning: false,
  },
  {
    id: 'validation-policies',
    title: 'menu.policies.validation',
    icon: 'home-check',
    link: ['/'],
    type: 'item',
    level: 1,
    hasWarning: false,
  },
  {
    id: 'payment-policies',
    title: 'menu.policies.payment',
    icon: 'credit-card',
    link: ['/'],
    type: 'item',
    level: 1,
    hasWarning: false,
  },
  {
    id: 'exchange-policies',
    title: 'menu.policies.exchange',
    icon: 'swap',
    link: ['/'],
    type: 'item',
    level: 1,
    hasWarning: false,
  },
];

export const POLICIES_MENU_ITEMS: MenuItemWithCounter[] = [
  {
    id: RouteUtils.SalesFeePoliciesPage.Base,
    title: 'menu.policies.sale_fee',
    icon: 'money',
    link: ['/', RouteUtils.SalesFeePoliciesPage.Base],
    type: 'item',
    level: 1,
    hasWarning: false,
    children: [
      {
        id: eContentStatuses.All,
        title: 'enums.content_statuses.all',
        icon: '',
        link: ['/', RouteUtils.SalesFeePoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      {
        id: eContentStatuses.Draft,
        title: 'enums.content_statuses.draft',
        icon: '',
        link: ['/', RouteUtils.SalesFeePoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.Draft },
      },
      {
        id: eContentStatuses.AdminPending,
        title: 'enums.content_statuses.admin_pending',
        icon: '',
        link: ['/', RouteUtils.SalesFeePoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminPending },
      },
      {
        id: eContentStatuses.AdminReviewing,
        title: 'enums.content_statuses.admin_reviewing',
        icon: '',
        link: ['/', RouteUtils.SalesFeePoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminReviewing },
      },
      {
        id: eContentStatuses.AdminRejected,
        title: 'enums.content_statuses.admin_rejected',
        icon: '',
        link: ['/', RouteUtils.SalesFeePoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminRejected },
      },
      {
        id: eContentStatuses.AdminApproved,
        title: 'enums.content_statuses.admin_approved',
        icon: '',
        link: ['/', RouteUtils.SalesFeePoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminApproved },
      },
      {
        id: eContentStatuses.AdminArchived,
        title: 'enums.content_statuses.admin_archived',
        icon: '',
        link: ['/', RouteUtils.SalesFeePoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminArchived },
      },
    ],
  },
  {
    id: 'delivery-fee-policies',
    title: 'menu.policies.delivery_fee',
    icon: 'hand-coins',
    link: ['/', RouteUtils.DeliveryFeePoliciesPage.Base],
    type: 'item',
    level: 1,
    hasWarning: false,
    children: [
      {
        id: eContentStatuses.All,
        title: 'enums.content_statuses.all',
        icon: '',
        link: ['/', RouteUtils.DeliveryFeePoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      {
        id: eContentStatuses.Draft,
        title: 'enums.content_statuses.draft',
        icon: '',
        link: ['/', RouteUtils.DeliveryFeePoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.Draft },
      },
      {
        id: eContentStatuses.AdminPending,
        title: 'enums.content_statuses.admin_pending',
        icon: '',
        link: ['/', RouteUtils.DeliveryFeePoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminPending },
      },
      {
        id: eContentStatuses.AdminReviewing,
        title: 'enums.content_statuses.admin_reviewing',
        icon: '',
        link: ['/', RouteUtils.DeliveryFeePoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminReviewing },
      },
      {
        id: eContentStatuses.AdminRejected,
        title: 'enums.content_statuses.admin_rejected',
        icon: '',
        link: ['/', RouteUtils.DeliveryFeePoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminRejected },
      },
      {
        id: eContentStatuses.AdminApproved,
        title: 'enums.content_statuses.admin_approved',
        icon: '',
        link: ['/', RouteUtils.DeliveryFeePoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminApproved },
      },
      {
        id: eContentStatuses.AdminArchived,
        title: 'enums.content_statuses.admin_archived',
        icon: '',
        link: ['/', RouteUtils.DeliveryFeePoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminArchived },
      },
    ],
  },
  {
    id: 'debt-policies',
    title: 'menu.policies.debt',
    icon: 'calculator',
    link: ['/', RouteUtils.DeptPoliciesPage.Base],
    type: 'item',
    level: 1,
    hasWarning: false,
    children: [
      {
        id: eContentStatuses.All,
        title: 'enums.content_statuses.all',
        icon: '',
        link: ['/', RouteUtils.DeptPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      {
        id: eContentStatuses.Draft,
        title: 'enums.content_statuses.draft',
        icon: '',
        link: ['/', RouteUtils.DeptPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.Draft },
      },
      {
        id: eContentStatuses.AdminPending,
        title: 'enums.content_statuses.admin_pending',
        icon: '',
        link: ['/', RouteUtils.DeptPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminPending },
      },
      {
        id: eContentStatuses.AdminReviewing,
        title: 'enums.content_statuses.admin_reviewing',
        icon: '',
        link: ['/', RouteUtils.DeptPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminReviewing },
      },
      {
        id: eContentStatuses.AdminRejected,
        title: 'enums.content_statuses.admin_rejected',
        icon: '',
        link: ['/', RouteUtils.DeptPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminRejected },
      },
      {
        id: eContentStatuses.AdminApproved,
        title: 'enums.content_statuses.admin_approved',
        icon: '',
        link: ['/', RouteUtils.DeptPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminApproved },
      },
      {
        id: eContentStatuses.AdminArchived,
        title: 'enums.content_statuses.admin_archived',
        icon: '',
        link: ['/', RouteUtils.DeptPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminArchived },
      },
    ],
  },
  {
    id: 'organization-registration-policies',
    title: 'menu.policies.organization_registration',
    icon: 'buildings',
    link: ['/', RouteUtils.OrganizationRegistrationPoliciesPage.Base],
    type: 'item',
    level: 1,
    hasWarning: false,
    children: [
      {
        id: eContentStatuses.All,
        title: 'enums.content_statuses.all',
        icon: '',
        link: ['/', RouteUtils.OrganizationRegistrationPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      {
        id: eContentStatuses.Draft,
        title: 'enums.content_statuses.draft',
        icon: '',
        link: ['/', RouteUtils.OrganizationRegistrationPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.Draft },
      },
      {
        id: eContentStatuses.AdminPending,
        title: 'enums.content_statuses.admin_pending',
        icon: '',
        link: ['/', RouteUtils.OrganizationRegistrationPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminPending },
      },
      {
        id: eContentStatuses.AdminReviewing,
        title: 'enums.content_statuses.admin_reviewing',
        icon: '',
        link: ['/', RouteUtils.OrganizationRegistrationPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminReviewing },
      },
      {
        id: eContentStatuses.AdminRejected,
        title: 'enums.content_statuses.admin_rejected',
        icon: '',
        link: ['/', RouteUtils.OrganizationRegistrationPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminRejected },
      },
      {
        id: eContentStatuses.AdminApproved,
        title: 'enums.content_statuses.admin_approved',
        icon: '',
        link: ['/', RouteUtils.OrganizationRegistrationPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminApproved },
      },
      {
        id: eContentStatuses.AdminArchived,
        title: 'enums.content_statuses.admin_archived',
        icon: '',
        link: ['/', RouteUtils.OrganizationRegistrationPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminArchived },
      },
    ],
  },
  {
    id: 'program-policies',
    title: 'menu.policies.program',
    icon: 'gift',
    link: ['/', RouteUtils.ProgramPoliciesPage.Base],
    type: 'collapse',
    level: 1,
    hasWarning: false,
    children: [
      {
        id: eContentStatuses.All,
        title: 'enums.content_statuses.all',
        icon: '',
        link: ['/', RouteUtils.ProgramPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      {
        id: eContentStatuses.Draft,
        title: 'enums.content_statuses.draft',
        icon: '',
        link: ['/', RouteUtils.ProgramPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.Draft },
      },
      {
        id: eContentStatuses.AdminPending,
        title: 'enums.content_statuses.admin_pending',
        icon: '',
        link: ['/', RouteUtils.ProgramPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminPending },
      },
      {
        id: eContentStatuses.AdminReviewing,
        title: 'enums.content_statuses.admin_reviewing',
        icon: '',
        link: ['/', RouteUtils.ProgramPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminReviewing },
      },
      {
        id: eContentStatuses.AdminRejected,
        title: 'enums.content_statuses.admin_rejected',
        icon: '',
        link: ['/', RouteUtils.ProgramPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminRejected },
      },
      {
        id: eContentStatuses.AdminApproved,
        title: 'enums.content_statuses.admin_approved',
        icon: '',
        link: ['/', RouteUtils.ProgramPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminApproved },
      },
      {
        id: eContentStatuses.AdminArchived,
        title: 'enums.content_statuses.admin_archived',
        icon: '',
        link: ['/', RouteUtils.ProgramPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminArchived },
      },
    ],
  },
  {
    id: 'privacy-policies',
    title: 'menu.policies.privacy',
    icon: 'gift',
    link: ['/', RouteUtils.PrivacyPoliciesPage.Base],
    type: 'item',
    level: 1,
    hasWarning: false,
    children: [
      {
        id: eContentStatuses.All,
        title: 'enums.content_statuses.all',
        icon: '',
        link: ['/', RouteUtils.PrivacyPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      {
        id: eContentStatuses.Draft,
        title: 'enums.content_statuses.draft',
        icon: '',
        link: ['/', RouteUtils.PrivacyPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.Draft },
      },
      {
        id: eContentStatuses.AdminPending,
        title: 'enums.content_statuses.admin_pending',
        icon: '',
        link: ['/', RouteUtils.PrivacyPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminPending },
      },
      {
        id: eContentStatuses.AdminReviewing,
        title: 'enums.content_statuses.admin_reviewing',
        icon: '',
        link: ['/', RouteUtils.PrivacyPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminReviewing },
      },
      {
        id: eContentStatuses.AdminRejected,
        title: 'enums.content_statuses.admin_rejected',
        icon: '',
        link: ['/', RouteUtils.PrivacyPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminRejected },
      },
      {
        id: eContentStatuses.AdminApproved,
        title: 'enums.content_statuses.admin_approved',
        icon: '',
        link: ['/', RouteUtils.PrivacyPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminApproved },
      },
      {
        id: eContentStatuses.AdminArchived,
        title: 'enums.content_statuses.admin_archived',
        icon: '',
        link: ['/', RouteUtils.PrivacyPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminArchived },
      },
    ],
  },
  {
    id: 'shipping-policies',
    title: 'menu.policies.shipping',
    icon: 'truck',
    link: ['/', RouteUtils.ShippingPoliciesPage.Base],
    type: 'item',
    level: 1,
    hasWarning: false,
    children: [
      {
        id: eContentStatuses.All,
        title: 'enums.content_statuses.all',
        icon: '',
        link: ['/', RouteUtils.ShippingPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      {
        id: eContentStatuses.Draft,
        title: 'enums.content_statuses.draft',
        icon: '',
        link: ['/', RouteUtils.ShippingPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.Draft },
      },
      {
        id: eContentStatuses.AdminPending,
        title: 'enums.content_statuses.admin_pending',
        icon: '',
        link: ['/', RouteUtils.ShippingPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminPending },
      },
      {
        id: eContentStatuses.AdminReviewing,
        title: 'enums.content_statuses.admin_reviewing',
        icon: '',
        link: ['/', RouteUtils.ShippingPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminReviewing },
      },
      {
        id: eContentStatuses.AdminRejected,
        title: 'enums.content_statuses.admin_rejected',
        icon: '',
        link: ['/', RouteUtils.ShippingPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminRejected },
      },
      {
        id: eContentStatuses.AdminApproved,
        title: 'enums.content_statuses.admin_approved',
        icon: '',
        link: ['/', RouteUtils.ShippingPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminApproved },
      },
      {
        id: eContentStatuses.AdminArchived,
        title: 'enums.content_statuses.admin_archived',
        icon: '',
        link: ['/', RouteUtils.ShippingPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminArchived },
      },
    ],
  },
  {
    id: 'inspection-policies',
    title: 'menu.policies.inspection',
    icon: 'home-check',
    link: ['/', RouteUtils.InspectionPoliciesPage.Base],
    type: 'item',
    level: 1,
    hasWarning: false,
    children: [
      {
        id: eContentStatuses.All,
        title: 'enums.content_statuses.all',
        icon: '',
        link: ['/', RouteUtils.InspectionPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      {
        id: eContentStatuses.Draft,
        title: 'enums.content_statuses.draft',
        icon: '',
        link: ['/', RouteUtils.InspectionPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.Draft },
      },
      {
        id: eContentStatuses.AdminPending,
        title: 'enums.content_statuses.admin_pending',
        icon: '',
        link: ['/', RouteUtils.InspectionPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminPending },
      },
      {
        id: eContentStatuses.AdminReviewing,
        title: 'enums.content_statuses.admin_reviewing',
        icon: '',
        link: ['/', RouteUtils.InspectionPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminReviewing },
      },
      {
        id: eContentStatuses.AdminRejected,
        title: 'enums.content_statuses.admin_rejected',
        icon: '',
        link: ['/', RouteUtils.InspectionPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminRejected },
      },
      {
        id: eContentStatuses.AdminApproved,
        title: 'enums.content_statuses.admin_approved',
        icon: '',
        link: ['/', RouteUtils.InspectionPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminApproved },
      },
      {
        id: eContentStatuses.AdminArchived,
        title: 'enums.content_statuses.admin_archived',
        icon: '',
        link: ['/', RouteUtils.InspectionPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminArchived },
      },
    ],
  },
  {
    id: 'payment-policies',
    title: 'menu.policies.payment',
    icon: 'credit-card',
    link: ['/', RouteUtils.PaymentPoliciesPage.Base],
    type: 'item',
    level: 1,
    hasWarning: false,
    children: [
      {
        id: eContentStatuses.All,
        title: 'enums.content_statuses.all',
        icon: '',
        link: ['/', RouteUtils.PaymentPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      {
        id: eContentStatuses.Draft,
        title: 'enums.content_statuses.draft',
        icon: '',
        link: ['/', RouteUtils.PaymentPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.Draft },
      },
      {
        id: eContentStatuses.AdminPending,
        title: 'enums.content_statuses.admin_pending',
        icon: '',
        link: ['/', RouteUtils.PaymentPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminPending },
      },
      {
        id: eContentStatuses.AdminReviewing,
        title: 'enums.content_statuses.admin_reviewing',
        icon: '',
        link: ['/', RouteUtils.PaymentPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminReviewing },
      },
      {
        id: eContentStatuses.AdminRejected,
        title: 'enums.content_statuses.admin_rejected',
        icon: '',
        link: ['/', RouteUtils.PaymentPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminRejected },
      },
      {
        id: eContentStatuses.AdminApproved,
        title: 'enums.content_statuses.admin_approved',
        icon: '',
        link: ['/', RouteUtils.PaymentPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminApproved },
      },
      {
        id: eContentStatuses.AdminArchived,
        title: 'enums.content_statuses.admin_archived',
        icon: '',
        link: ['/', RouteUtils.PaymentPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminArchived },
      },
    ],
  },
  {
    id: 'return-policies',
    title: 'menu.policies.return',
    icon: 'swap',
    link: ['/', RouteUtils.ReturnPoliciesPage.Base],
    type: 'item',
    level: 1,
    hasWarning: false,
    children: [
      {
        id: eContentStatuses.All,
        title: 'enums.content_statuses.all',
        icon: '',
        link: ['/', RouteUtils.ReturnPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      {
        id: eContentStatuses.Draft,
        title: 'enums.content_statuses.draft',
        icon: '',
        link: ['/', RouteUtils.ReturnPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.Draft },
      },
      {
        id: eContentStatuses.AdminPending,
        title: 'enums.content_statuses.admin_pending',
        icon: '',
        link: ['/', RouteUtils.ReturnPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminPending },
      },
      {
        id: eContentStatuses.AdminReviewing,
        title: 'enums.content_statuses.admin_reviewing',
        icon: '',
        link: ['/', RouteUtils.ReturnPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminReviewing },
      },
      {
        id: eContentStatuses.AdminRejected,
        title: 'enums.content_statuses.admin_rejected',
        icon: '',
        link: ['/', RouteUtils.ReturnPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminRejected },
      },
      {
        id: eContentStatuses.AdminApproved,
        title: 'enums.content_statuses.admin_approved',
        icon: '',
        link: ['/', RouteUtils.ReturnPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminApproved },
      },
      {
        id: eContentStatuses.AdminArchived,
        title: 'enums.content_statuses.admin_archived',
        icon: '',
        link: ['/', RouteUtils.ReturnPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminArchived },
      },
    ],
  },
  {
    id: 'other-policies',
    title: 'menu.policies.other',
    icon: 'swap',
    link: ['/', RouteUtils.OtherPoliciesPage.Base],
    type: 'item',
    level: 1,
    hasWarning: false,
    children: [
      {
        id: eContentStatuses.All,
        title: 'enums.content_statuses.all',
        icon: '',
        link: ['/', RouteUtils.OtherPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      {
        id: eContentStatuses.Draft,
        title: 'enums.content_statuses.draft',
        icon: '',
        link: ['/', RouteUtils.OtherPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.Draft },
      },
      {
        id: eContentStatuses.AdminPending,
        title: 'enums.content_statuses.admin_pending',
        icon: '',
        link: ['/', RouteUtils.OtherPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminPending },
      },
      {
        id: eContentStatuses.AdminReviewing,
        title: 'enums.content_statuses.admin_reviewing',
        icon: '',
        link: ['/', RouteUtils.OtherPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminReviewing },
      },
      {
        id: eContentStatuses.AdminRejected,
        title: 'enums.content_statuses.admin_rejected',
        icon: '',
        link: ['/', RouteUtils.OtherPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminRejected },
      },
      {
        id: eContentStatuses.AdminApproved,
        title: 'enums.content_statuses.admin_approved',
        icon: '',
        link: ['/', RouteUtils.OtherPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminApproved },
      },
      {
        id: eContentStatuses.AdminArchived,
        title: 'enums.content_statuses.admin_archived',
        icon: '',
        link: ['/', RouteUtils.OtherPoliciesPage.Base],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminArchived },
      },
    ],
  },
];

export const GROUPS_MENU_ITEMS: MenuItemWithCounter[] = [
  {
    id: 'groups',
    title: 'menu.groups',
    icon: 'group',
    link: ['/', RouteUtils.GroupsPage.Base],
    type: 'item',
    level: 1,
    hasWarning: false,
    children: [
      {
        id: eContentStatuses.All,
        title: 'enums.content_statuses.all',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      {
        id: eContentStatuses.New,
        title: 'enums.content_statuses.new',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.New },
      },
      {
        id: eContentStatuses.AdminPending,
        title: 'enums.content_statuses.admin_pending',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminPending },
      },
      {
        id: eContentStatuses.AdminReviewing,
        title: 'enums.content_statuses.admin_reviewing',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminReviewing },
      },
      {
        id: eContentStatuses.AdminRejected,
        title: 'enums.content_statuses.admin_rejected',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminRejected },
      },
      {
        id: eContentStatuses.AdminApproved,
        title: 'enums.content_statuses.admin_approved',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminApproved },
      },
      {
        id: eContentStatuses.AdminArchived,
        title: 'enums.content_statuses.admin_archived',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminArchived },
      },
    ],
  },
  {
    id: 'categories',
    title: 'menu.categories.base',
    icon: 'product-list',
    link: ['/', RouteUtils.CategoriesPage.Base],
    type: 'item',
    level: 1,
    hasWarning: false,
    children: [
      {
        id: eContentStatuses.All,
        title: 'enums.content_statuses.all',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      {
        id: eContentStatuses.Draft,
        title: 'enums.content_statuses.draft',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.Draft },
      },
      {
        id: eContentStatuses.AdminPending,
        title: 'enums.content_statuses.admin_pending',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminPending },
      },
      {
        id: eContentStatuses.AdminReviewing,
        title: 'enums.content_statuses.admin_reviewing',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminReviewing },
      },
      {
        id: eContentStatuses.AdminRejected,
        title: 'enums.content_statuses.admin_rejected',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminRejected },
      },
      {
        id: eContentStatuses.AdminApproved,
        title: 'enums.content_statuses.admin_approved',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminApproved },
      },
      {
        id: eContentStatuses.AdminArchived,
        title: 'enums.content_statuses.admin_archived',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminArchived },
      },
    ],
  },

  {
    id: 'attributes',
    title: 'menu.categories.attributes',
    icon: 'packages',
    link: ['/', RouteUtils.AttributesPage.Base],
    type: 'item',
    level: 1,
    children: [
      {
        id: eContentStatuses.All,
        title: 'enums.content_statuses.all',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      {
        id: eContentStatuses.Draft,
        title: 'enums.content_statuses.draft',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.Draft },
      },
      {
        id: eContentStatuses.AdminPending,
        title: 'enums.content_statuses.admin_pending',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminPending },
      },
      {
        id: eContentStatuses.AdminReviewing,
        title: 'enums.content_statuses.admin_reviewing',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminReviewing },
      },
      {
        id: eContentStatuses.AdminRejected,
        title: 'enums.content_statuses.admin_rejected',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminRejected },
      },
      {
        id: eContentStatuses.AdminApproved,
        title: 'enums.content_statuses.admin_approved',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminApproved },
      },
      {
        id: eContentStatuses.AdminArchived,
        title: 'enums.content_statuses.admin_archived',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminArchived },
      },
    ],
    hasWarning: false,
  },
  {
    id: 'sale_units',
    title: 'menu.categories.sale_units',
    icon: 'hand-soap',
    link: ['/', RouteUtils.SaleUnitsPage.Base],
    type: 'item',
    level: 1,
    children: [
      {
        id: eContentStatuses.All,
        title: 'enums.content_statuses.all',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      {
        id: eContentStatuses.New,
        title: 'enums.content_statuses.new',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.New },
      },
      {
        id: eContentStatuses.AdminPending,
        title: 'enums.content_statuses.admin_pending',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminPending },
      },
      {
        id: eContentStatuses.AdminReviewing,
        title: 'enums.content_statuses.admin_reviewing',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminReviewing },
      },
      {
        id: eContentStatuses.AdminRejected,
        title: 'enums.content_statuses.admin_rejected',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminRejected },
      },
      {
        id: eContentStatuses.AdminApproved,
        title: 'enums.content_statuses.admin_approved',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminApproved },
      },
      {
        id: eContentStatuses.AdminArchived,
        title: 'enums.content_statuses.admin_archived',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminArchived },
      },
    ],
    hasWarning: false,
  },
  {
    id: 'brands',
    title: 'menu.categories.brands',
    icon: 'medal',
    link: ['/', RouteUtils.BrandsPage.Base],
    type: 'item',
    level: 1,
    children: [
      {
        id: eContentStatuses.All,
        title: 'enums.content_statuses.all',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      {
        id: eContentStatuses.Draft,
        title: 'enums.content_statuses.draft',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.New },
      },
      {
        id: eContentStatuses.AdminPending,
        title: 'enums.content_statuses.admin_pending',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminPending },
      },
      {
        id: eContentStatuses.AdminReviewing,
        title: 'enums.content_statuses.admin_reviewing',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminReviewing },
      },
      {
        id: eContentStatuses.AdminRejected,
        title: 'enums.content_statuses.admin_rejected',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminRejected },
      },
      {
        id: eContentStatuses.AdminApproved,
        title: 'enums.content_statuses.admin_approved',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminApproved },
      },
      {
        id: eContentStatuses.AdminArchived,
        title: 'enums.content_statuses.admin_archived',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminArchived },
      },
    ],
  },
];

export const PACKED_UNITS_MENU_ITEMS: MenuItemWithCounter[] = [
  {
    id: 'categories',
    title: 'menu.categories.base',
    icon: 'product-list',
    link: ['/', RouteUtils.CategoriesPage.Base],
    type: 'item',
    level: 1,
    hasWarning: false,
  },
  {
    id: 'groups',
    title: 'menu.groups',
    icon: 'group',
    link: ['/', RouteUtils.GroupsPage.Base],
    type: 'item',
    level: 1,
    hasWarning: false,
  },
  {
    id: 'product_units',
    title: 'menu.categories.product_units',
    icon: 'packages',
    link: ['/', RouteUtils.PackedUnitsPage.Base],
    type: 'item',
    level: 1,
    children: [],
    hasWarning: false,
  },
  // {
  //   id: 'sizing_units',
  //   title: 'menu.categories.sizing_units',
  //   icon: 'codepen',
  //   link: ['#'],
  //   type: 'item',
  //   level: 1,
  //   children: [],
  //   hasWarning: false,
  // },
  // {
  //   id: 'volume_units',
  //   title: 'menu.categories.volume_units',
  //   icon: 'drop-half',
  //   link: ['#'],
  //   type: 'item',
  //   level: 1,
  //   children: [],
  //   hasWarning: false,
  // },
  // {
  //   id: 'weight_units',
  //   title: 'menu.categories.weight_units',
  //   icon: 'test-tube',
  //   link: ['#'],
  //   type: 'item',
  //   level: 1,
  //   children: [],
  //   hasWarning: false,
  // },
];

export const USERS_MENU_ITEMS: MenuItemWithCounter[] = [
  {
    id: 'user',
    title: 'menu.users',
    icon: 'user',
    link: ['.'],
    type: 'collapse',
    children: [
      {
        id: eAccountStatus.All.toString(),
        title: 'enums.user_statuses.all',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eAccountStatus.All },
      },
      {
        id: eAccountStatus.Locked.toString(),
        title: 'enums.user_statuses.locked',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eAccountStatus.Disabled },
      },
      {
        id: eAccountStatus.Activated.toString(),
        title: 'enums.user_statuses.active',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eAccountStatus.Activated },
      },
    ],
  },
];

export const GENERAL_SETTING_MENU_ITEMS: MenuItemWithCounter[] = [
  {
    id: 'authentication',
    title: 'menu.setting',
    icon: 'shield-warning',
    link: ['/', RouteUtils.GeneralSettingPage.Base],
    type: 'collapse',
    children: [
      {
        id: eContentStatuses.All,
        title: 'enums.content_statuses.all',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      {
        id: eContentStatuses.Draft,
        title: 'enums.content_statuses.draft',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.Draft },
      },
      {
        id: eContentStatuses.AdminPending,
        title: 'enums.content_statuses.admin_pending',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminPending },
      },
      {
        id: eContentStatuses.AdminReviewing,
        title: 'enums.content_statuses.admin_reviewing',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminReviewing },
      },
      {
        id: eContentStatuses.AdminRejected,
        title: 'enums.content_statuses.admin_rejected',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminRejected },
      },
      {
        id: eContentStatuses.AdminApproved,
        title: 'enums.content_statuses.admin_approved',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminApproved },
      },
      {
        id: eContentStatuses.AdminArchived,
        title: 'enums.content_statuses.admin_archived',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminArchived },
      },
    ],
    level: 1,
    hasWarning: false,
  },
];

export const AGREEMENT_MENU_ITEMS: MenuItemWithCounter[] = [
  {
    id: 'agreements',
    title: 'menu.agreements',
    icon: 'file',
    link: ['/', RouteUtils.AgreementPage.Base],
    queryParams: { status: eContentStatuses.All },
    type: 'collapse',
    children: [
      {
        id: eContentStatuses.All,
        title: 'enums.content_statuses.all',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      {
        id: eContentStatuses.Draft,
        title: 'enums.content_statuses.draft',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.Draft },
      },
      {
        id: eContentStatuses.AdminPending,
        title: 'enums.content_statuses.admin_pending',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminPending },
      },
      {
        id: eContentStatuses.AdminReviewing,
        title: 'enums.content_statuses.admin_reviewing',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminReviewing },
      },
      {
        id: eContentStatuses.AdminRejected,
        title: 'enums.content_statuses.admin_rejected',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminRejected },
      },
      {
        id: eContentStatuses.AdminApproved,
        title: 'enums.content_statuses.admin_approved',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminApproved },
      },
      {
        id: eContentStatuses.AdminArchived,
        title: 'enums.content_statuses.admin_archived',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminArchived },
      },
    ],
    level: 1,
    hasWarning: false,
  },
];

export const QA_MENU_ITEMS: MenuItemWithCounter[] = [
  {
    id: 'question-and-answer',
    title: 'menu.qa',
    icon: 'communication',
    link: ['/', RouteUtils.QuestionAndAnswer.Base],
    type: 'collapse',
    children: [
      {
        id: 'all',
        title: 'enums.content_statuses.all',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      {
        id: 'draft',
        title: 'enums.content_statuses.draft',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.Draft },
      },
      {
        id: 'admin_pending',
        title: 'enums.content_statuses.admin_pending',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.SellerPending },
      },
      {
        id: 'admin_reviewing',
        title: 'enums.content_statuses.admin_reviewing',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminReviewing },
      },
      {
        id: 'admin_rejected',
        title: 'enums.content_statuses.admin_rejected',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminRejected },
      },
      {
        id: 'admin_approved',
        title: 'enums.content_statuses.admin_approved',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminApproved },
      },
      {
        id: 'admin_archived',
        title: 'enums.content_statuses.admin_archived',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminArchived },
      },
    ],
    level: 1,
    hasWarning: false,
  },
];

export const USER_GUIDE_MENU_ITEMS: MenuItemWithCounter[] = [
  {
    id: 'user-guide',
    title: 'menu.user-guide',
    icon: 'communication',
    link: ['/', RouteUtils.UserGuide.Base],
    type: 'collapse',
    children: [
      {
        id: 'all',
        title: 'enums.content_statuses.all',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      // {
      //   id: 'draft',
      //   title: 'enums.content_statuses.draft',
      //   icon: 'plus',
      //   link: ['.'],
      //   type: 'item',
      //   level: 2,
      //   queryParams: { status: eContentStatuses.Draft },
      // },
      // {
      //   id: 'admin_pending',
      //   title: 'enums.content_statuses.admin_pending',
      //   icon: 'plus',
      //   link: ['.'],
      //   type: 'item',
      //   level: 2,
      //   queryParams: { status: eContentStatuses.SellerPending },
      // },
      // {
      //   id: 'admin_reviewing',
      //   title: 'enums.content_statuses.admin_reviewing',
      //   icon: 'plus',
      //   link: ['.'],
      //   type: 'item',
      //   level: 2,
      //   queryParams: { status: eContentStatuses.AdminReviewing },
      // },
      // {
      //   id: 'admin_rejected',
      //   title: 'enums.content_statuses.admin_rejected',
      //   icon: 'plus',
      //   link: ['.'],
      //   type: 'item',
      //   level: 2,
      //   queryParams: { status: eContentStatuses.AdminRejected },
      // },
      // {
      //   id: 'admin_approved',
      //   title: 'enums.content_statuses.admin_approved',
      //   icon: 'plus',
      //   link: ['.'],
      //   type: 'item',
      //   level: 2,
      //   queryParams: { status: eContentStatuses.AdminApproved },
      // },
      // {
      //   id: 'admin_archived',
      //   title: 'enums.content_statuses.admin_archived',
      //   icon: 'plus',
      //   link: ['.'],
      //   type: 'item',
      //   level: 2,
      //   queryParams: { status: eContentStatuses.AdminArchived },
      // },
    ],
    level: 1,
    hasWarning: false,
  },
];

export const NOTIFICATION_MENU_ITEMS: MenuItemWithCounter[] = [
  {
    id: RouteUtils.NotificationManagement.Base,
    title: 'menu.notification',
    icon: 'bell-ringing',
    link: ['/', RouteUtils.NotificationManagement.Base],
    type: 'collapse',
    level: 1,
    children: [
      {
        id: eContentStatuses.All,
        title: 'enums.content_statuses.all',
        icon: '',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      {
        id: eContentStatuses.Draft,
        title: 'enums.content_statuses.draft',
        icon: '',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.Draft },
      },
      {
        id: eContentStatuses.AdminPending,
        title: 'enums.content_statuses.admin_pending',
        icon: '',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminPending },
      },
      {
        id: eContentStatuses.AdminReviewing,
        title: 'enums.content_statuses.admin_reviewing',
        icon: '',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminReviewing },
      },
      {
        id: eContentStatuses.AdminRejected,
        title: 'enums.content_statuses.admin_rejected',
        icon: '',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminRejected },
      },
      {
        id: eContentStatuses.AdminApproved,
        title: 'enums.content_statuses.admin_approved',
        icon: '',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminApproved },
      },
      // {
      //   id: 'admin_archived',
      //   title: 'enums.content_statuses.admin_archived',
      //   icon: 'plus',
      //   link: ['.'],
      //   type: 'item',
      //   level: 2,
      //   queryParams: { status: eContentStatuses.AdminArchived },
      // },
    ],
    hasWarning: false,
  },
];

export const CITIES_MENU_ITEMS: MenuItemWithCounter[] = [
  {
    id: 'product_units',
    title: 'menu.area_trees.cities',
    icon: 'packages',
    link: ['/', RouteUtils.AreaTreePage.Base],
    type: 'item',
    level: 1,
    children: [],
    hasWarning: false,
  },
];

export const CONTACT_AND_SUPPORT_MENU_ITEMS: MenuItemWithCounter[] = [
  {
    id: 'contact-and-support-contact',
    title: 'menu.contact',
    icon: '',
    link: ['/', RouteUtils.ContactAndSupport.Contact],
    type: 'item',
    level: 1,
    hasWarning: false,
    children: [],
  },
  {
    id: 'contact-and-support-guide',
    title: 'menu.guide',
    icon: '',
    link: ['/', RouteUtils.UserGuide.Base],
    type: 'item',
    level: 1,
    hasWarning: false,
    children: [],
  },
];

export const COMMUNITY_STANDARDS_MENU_ITEMS: MenuItemWithCounter[] = [
  {
    id: 'community_standards',
    title: 'menu.community_standards.base',
    icon: 'users-three',
    link: ['/', RouteUtils.CommunityStandards.Base],
    type: 'collapse',
    children: [
      {
        id: eContentStatuses.All,
        title: 'enums.content_statuses.all',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.All },
      },
      {
        id: eContentStatuses.Draft,
        title: 'enums.content_statuses.draft',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.Draft },
      },
      {
        id: eContentStatuses.AdminPending,
        title: 'enums.content_statuses.admin_pending',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminPending },
      },
      {
        id: eContentStatuses.AdminReviewing,
        title: 'enums.content_statuses.admin_reviewing',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminReviewing },
      },
      {
        id: eContentStatuses.AdminApproved,
        title: 'enums.content_statuses.admin_approved',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminApproved },
      },
      {
        id: eContentStatuses.AdminRejected,
        title: 'enums.content_statuses.admin_rejected',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminRejected },
      },
      {
        id: eContentStatuses.AdminArchived,
        title: 'enums.content_statuses.admin_archived',
        icon: 'plus',
        link: ['.'],
        type: 'item',
        level: 2,
        queryParams: { status: eContentStatuses.AdminArchived },
      },
    ],
    level: 1,
    hasWarning: false,
  },
];
